import React from 'react'
import Head from 'next/head'
import Layout from '../layout/layout'

const Login = () => {
  return (
    <Layout>
    <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>
        <h1 className='text-3xl font-bold'>Login</h1>
    </div>
    </Layout>
    
  )
}

export default Login