import React, { useState } from 'react'
import Head from 'next/head'
import Layout from '../layout/layout'
import Link from 'next/link'
import styles from '../styles/Form.module.css';
import Image from 'next/image';
import { HiAtSymbol, HiFingerPrint, HiOutlineUser } from "react-icons/hi";

const Register = () => {
    const [ show, setShow ] = useState({ password: false, confirmPassword: false })
  return (
    <Layout>
    <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>
         <section className='w-3/4 mx-auto flex flex-col gap-10'>
            <div className='title'>
                <h1 className='text-gray-800 text-4xl  font-bold p4'>Register</h1>
                <p className='w-3/4 mx-auto text-gray-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, officia?</p>

            </div>

            {/* Form */}
            <form className='flex flex-col gap-5'>
                <div className={styles.input_group}>
                    <input 
                    type="text"
                    name='name'
                    placeholder='Name'
                    className={styles.input_text}
                    />
                    <span className='icon flex items-center px-4'>
                        <HiOutlineUser size={25} />
                    </span>
                </div>
                <div className={styles.input_group}>
                    <input 
                    type="email"
                    name='email'
                    placeholder='Email'
                    className={styles.input_text}
                    />
                    <span className='icon flex items-center px-4'>
                        <HiAtSymbol size={25} />
                    </span>
                </div>
                <div className={styles.input_group}>
                    <input 
                    type={`${show.password ? "text" : "password"}`}
                    name='password'
                    placeholder='Password'
                    className={styles.input_text}
                    />
                     <span className='icon flex items-center px-4' onClick={() => setShow({ ...show, password: !show.password})}>
                        <HiFingerPrint size={25} />
                    </span>
                </div>
                <div className={styles.input_group}>
                    <input 
                    type={`${show.confirmPassword ? "text" : "password"}`}
                    name='confirmPassword'
                    placeholder='Confirm password'
                    className={styles.input_text}
                    />
                     <span className='icon flex items-center px-4' onClick={() => setShow({ ...show, confirmPassword: !show.confirmPassword})}>
                        <HiFingerPrint size={25} />
                    </span>
                </div>

               {/* login buttons */}
                <div className={styles.button}>
                    <button type='submit'>
                        Register
                    </button>
                </div>
            </form>

            {/* Bottom */}
            <p className='text-center text-red-400 '>
                Already have an account? <Link href={'/login'}><a className='text-blue-700'>Login</a></Link>
            </p>
        </section>
    </div>
    </Layout>
    
  )
}

export default Register