import React from 'react'
import Head from 'next/head'

const Register = () => {
  return (
    <>
    <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>
        <h1 className='text-3xl font-bold'>Register</h1>
    </div>
    </>
    
  )
}

export default Register